### ISSUE TITLE
Publish the library to Maven Central

### ISSUE THREAD

**Issue by maddingo** [yskszk63/jnhttp-multipartformdata-bodypublisher#1]
This is a cool library. Would you consider publishing it to Maven Central. The guide how to do this is on https://central.sonatype.org/publish/publish-guide/

**Comment by yskszk63** [comment]
@maddingo 
Sorry for the late reply.

[Ticket](https://issues.sonatype.org/browse/OSSRH-85190) Created.

Please note that we have changed the groupId and package name to publish to Maven Central.

**Comment by yskszk63** [comment]
Published to maven central.

https://search.maven.org/artifact/io.github.yskszk63/jnhttp-multipartformdata-bodypublisher/0.0.1/jar
